# -*- coding: utf-8 -*-
#
# This file is part of kwalitee
# Copyright (C) 2014, 2015 CERN.
#
# kwalitee is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# kwalitee is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kwalitee; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this licence, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

language: python

python:
 - "2.6"
 - "2.7"
 - "3.3"
# TODO re-enable after gabrielfalcao/HTTPretty#193 will be merged
# - "3.4"

env:
  global:
    - LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  matrix:
    - WITH_PYGIT2=true
    - WITH_PYGIT2=false

install:
  - sudo apt-get install -qy python-dev libffi-dev cmake
  - pip install --upgrade pip --use-mirrors
  # libgit2-dev isn't available from ubuntu, and ppa:dennis doesn't work with
  # the Ubuntu LTS version travis is using.
  - $WITH_PYGIT2 && wget https://github.com/libgit2/libgit2/archive/v0.21.0.tar.gz || true
  - $WITH_PYGIT2 && tar xzf v0.21.0.tar.gz || true
  - $WITH_PYGIT2 && cd libgit2-0.21.0/ || true
  - $WITH_PYGIT2 && cmake . && make && sudo make install || true
  - $WITH_PYGIT2 && cd .. || true
  - $WITH_PYGIT2 && pip install cffi pygit2 --use-mirrors || true
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-docs.txt
  - travis_retry pip install coveralls pytest --use-mirrors

script:
  - python setup.py test -a "tests --cov-config .coveragerc --cov kwalitee --cov-report term-missing"
  - sphinx-build -vnNW docs _build

after_success:
  - coveralls

notifications:
  email: false
